### PR TITLE
Style updates

### PR DESCRIPTION
**Pull request by lukebemish**
Here's my attempt at style pokes, put here as a draft PR so that it's easily visible.

(see discussion around https://discord.com/channels/313125603924639766/1155593265379283035/1155600668451672085)

Current state (updates 25-Sep-2023):
image

------------------
Preview URL: https://pr-4.neoforged-website-previews.pages.dev

### CODE REVIEW

**Comment by Poopooracoocoo** [comment]
Not super keen on that background colour. I'd go much lighter and redder. And the larger max-width makes it harder to read.

**Comment by lukebemish** [comment]
The background color is taken straight from the logo; I could try a different one but honestly I'm not entirely sold contrast wise with some other greys. The max width... on my screen it's definitely readable at that width, and keep in mind that the width is actually capped so on larger screens it'll limit how wide it is. (My screen is pretty dang small because it's a laptop)

**Comment by lukebemish** [comment]
Updated the width stuff after a bit of poking around - it should now look reasonable on both very wide and very small screens

**Review by AterAnimAvis — APPROVED** [review]

**Comment by Poopooracoocoo** [comment]
Would you please consider reducing the max width more?

**Comment by lukebemish** [comment]
It's capped at the lower of 1920 or 80% of the screen except on small screens. From the screenshots I've seen on larger screens it seems to be fine, but if you could share a screenshot of what you see the issue as being that would be helpful

**Comment by lukebemish** [comment]
(ignore the broken download button for now. It's funky because of some hard coding in the old system I need to fix)

**Comment by cpw** [comment]
I wholeheartedly approve. :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by Poopooracoocoo** [comment]
The issue is that larger widths make it harder to read as it creates more distance for your eyes to go to the next line. Try reading the news post, for example. I have the same issues with the width on my desktop and on my laptop. I feel that a max width of 1920px is too much and a min width of 1380px is too much.

**Comment by cpw** [comment]
Delaying the whole restyle because of trivial tweaks to widths is not something I want to happen. I think it is excellently readable across a variety of devices and browser sizes.

**Comment by Poopooracoocoo** [comment]
I didn't ask for it to be delayed lol. I requested changes a while ago. Narrower widths are _standard_ on websites.

**Pull request merged**
