### PR TITLE
Hopefully fix google text result images

### PR DESCRIPTION
**Pull request by lukebemish**
So you know how neoforge's search results seem to show random images as the thumbnail image? Sometimes curle's profile picture, sometimes tech's? ~~This hopefully fixes this, using the thumbnail meta documented [here](https://support.google.com/programmable-search/answer/1626955?hl=en).~~ (This meta is just for google custom search engines, it seems - let's see if the `og:image` tag helps stuff instead). It's hard for me to actually test, unfortunately.

------------------
Preview URL: https://pr-30.neoforged-website-previews.pages.dev

### CODE REVIEW

**Comment by lukebemish** [comment]
Need to do some more reading - those docs appear to only be for google custom search engines, so I need to check and figure out whether it applies to normal google search results too. Converting to a draft for now

**Comment by lukebemish** [comment]
Alright, decided to approach this instead with the `og:image` meta tag, and making sure that gets set - I also changed around the title of the main page to communicate the fact that this is the home page for the neoforged project, cause I noticed that being strange in embed cards.

**Comment by UltimatChamp** [comment]
Wouldn't this work:
Screenshot_20240322_204744

**Comment by lukebemish** [comment]
> Wouldn't this work:
> Screenshot_20240322_204744
> 

Could work I suppose; seems like the brute force approach, but yeah, we could just force google to not index the profile images at all. Not sure if that would hit search rankings though

**Pull request merged**
