### PR TITLE
Better Installer Download Page

### PR DESCRIPTION
**Pull request by UltimatChamp**
This is a better looking installer file downloading UI, inspired from the _https://files.minecraftforge.net/net/minecraftforge/forge/_ website.

I couldn't find the `Note: this file is still called forge because we’re trying to maintain compatibility with launchers, assuming they don’t hardcode things too much.` para.
Please change it to --> `Note: The installer file is still called <b><i>forge</i></b>, because we’re trying to maintain compatibility with launchers, assuming they don’t hardcode things too much.`

------------------
Preview URL: https://pr-7.neoforged-website-previews.pages.dev

### CODE REVIEW

**Comment by sciwhiz12** [comment]
Whoops. Pressed the wrong button.

**Comment by PlatinPython** [comment]
Well, whatever you tried to do, it did not work and broke all the CSS instead
<details>
  <summary>Spoiler because bright</summary>
  
</details>

**Comment by UltimatChamp** [comment]
Oopsss... It didn't do this in my testing. It somehow undo-s the changes I brought to. Maybe conflicting with the reloading version of the installer.

**Comment by UltimatChamp** [comment]
Hopefully going to be resolved by tomorrow!

**Comment by lukebemish** [comment]
Some notes:
- can we please not use IDs to target stuff for styling?
- what's up with the colors? I'd pick something in-palette if possible
- why does this use a whole new style sheet? And if you're putting it in `assets` you need to handle it through the normal hugo resources system. That's why it's broken now
- not sold on the MDK zip link. We should be encouraging people to use git, not linking them a zip!
- `<button id="versions" onClick="window.location.href='https://maven.neoforged.net/#/releases/net/neoforged/forge';">See all versions</button>` erm... isn't that called an `a` tag? No reason to use a button and JS

**Comment by AterAnimAvis** [comment]
To add the current naming of the file as `css/style.css` is overriding our theme's style.css https://github.com/neoforged/websites/blob/main/themes/mainroad/assets/css/style.css which is why the site looks extra broken on the preview.
The JS file hasn't been updated for your html changes, so they will just be overriden back to the origin html.

**Comment by ChampionAsh5357** [comment]
Where are those SVGs from and what are their licenses? Also I'm not sure how those SVGs make sense beside from the changelog. The installer makes me think I'm downloading a text file while the mdk just doesn't make sense. If there's already been discussion about this, then I'll withdraw my comment.

**Comment by cpw** [comment]
I agree with @lukebemish - the MDK is not something we should be offering a link to download - the MDK is a template repo now. Modders have choices. Also, your CSS is completely screwed up. This alone means this is unusable. 


Where are the SVGs from? Are they from a free SVG resource? If so, can you provide links?

**Comment by UltimatChamp** [comment]
> I agree with @lukebemish - the MDK is not something we should be offering a link to download - the MDK is a template repo now. Modders have choices. Also, your CSS is completely screwed up. This alone means this is unusable.
> 
> Where are the SVGs from? Are they from a free SVG resource? If so, can you provide links?

A big thanks to [**IconFinder**](https://www.iconfinder.com/) for providing _[these images](https://github.com/neoforged/neoforged-website/tree/main/assets/img/content/links)_ for free, under the **_[CC0 1.0 Universal (CC0 1.0) Public Domain Dedication](https://creativecommons.org/publicdomain/zero/1.0/) License_**!

##### Make sure to check their website to download free stock images. 

This is the credits.md file that you can find here for the images: https://github.com/neoforged/websites/pull/7/commits/142ae0d1828737f5c3b45cd216cc03ea22baa6eb#diff-f5c60ea9f1afb6b2069e5d59ac405c73401c938d01ef164c79f2cad04ea08ac9

**Comment by UltimatChamp** [comment]
The work is almost completed. Going to fix the css now.

**Comment by UltimatChamp** [comment]
Just waiting for neoforged-pages-deployment to generate 😪

**Comment by lukebemish** [comment]
Some notes in general:
- border radius when nothing else has it?
- random out of palette colors that are hardcoded into that location?
- white border, apparently?
- drop shadow, behind said border radius? Not sold
- referencing svg files with an img tag? Should be inlined.

Overall, I'm really not sold with this change. It's got a lot of issues

**Comment by UltimatChamp** [comment]
Took a lot of time. The website should be ready now...

**Comment by UltimatChamp** [comment]
Screenshot-2023-10-10-161255

**Comment by lukebemish** [comment]
Inline your SVGs with the proper Hugo method, not by literally pasting the SVG text. Also that border radius still looks bad. You'll also need to rebase it because the dark mode support PR changed some of the underlying style stuff to allow that.

**Comment by lukebemish** [comment]
Cloned and ran it locally... this is what it looks like. The "neo" in parentheses is unnecessary, besides the fact that it looks terrible.
image
And on dark mode it's even worse:
image
Mobile:
image
Also `#a9aeb1` is still very out of palette, and we have in-palette colors that would work so...

That said, you messed up your SVGs too. The changelog SVG is the same shape as the download SVG, but smaller, meaning that the lines in it look too thin. Also, why the ease-in-out transition on the file info?

You're still hardcoding colors on the installer icons, from what I can see...

**Comment by UltimatChamp** [comment]
And I broke the js now
Why is there a text background now...
Gotta check it OUT! 

BTW please give some suggestions on the search menu and what color should I use instead of `#a9aeb1`

**Comment by lukebemish** [comment]
Check the colors in the neoforged logo

**Comment by lukebemish** [comment]
If you're inlining the SVGs, no clue why you're doing it that way. Just do what the theme already does...

**Comment by UltimatChamp** [comment]
I'm new to partials and the entire concept of Hugo. There should not be any errors, but still.
Please check if the link to the svgs in the `svg.html` file is correct... ooh a reply

**Comment by UltimatChamp** [comment]
I think I found the format used: `{{ partial "svg/installer_icons/installer.svg" }}`

**Comment by lukebemish** [comment]
Any reason you're using PNG files there for the icons? That's, like... a bad idea for a number of reasons. Not least of which is that the color can't be controlled by CSS, and that without a lot more work they result in page drift on loading...

**Comment by UltimatChamp** [comment]
I'm going to change the js to only set the version and `<a>`

**Comment by UltimatChamp** [comment]
Ging to use svg, now

**Comment by UltimatChamp** [comment]
Everything is OK, but how to set the links at the center vertically. Going to make it ready for review, still.

**Comment by lukebemish** [comment]
Erm, any reason you're using JS to center the links...? Seems like that should be CSS to me

**Comment by UltimatChamp** [comment]
I was trying that for an al

> Erm, any reason you're using JS to center the links...? Seems like that should be CSS to me

I was trying to get it to work. But it didn't. Css and js
Any suggestions.

**Comment by UltimatChamp** [comment]
See files changed.

**Comment by lukebemish** [comment]
> I was trying that for an al
> 
> > Erm, any reason you're using JS to center the links...? Seems like that should be CSS to me
> 
> I was trying to get it to work. But it didn't. Css and js Any suggestions.

I mean, just center the text with CSS? What exactly were you trying to do that didn't work?

**Comment by UltimatChamp** [comment]
> > I was trying that for an al
> > > Erm, any reason you're using JS to center the links...? Seems like that should be CSS to me
> > 
> > 
> > I was trying to get it to work. But it didn't. Css and js Any suggestions.
> 
> I mean, just center the text with CSS? What exactly were you trying to do that didn't work?

I'm not taking about text. I'm talking about the images.

**Comment by UltimatChamp** [comment]
Found a method to get the items centered. The work is done!

**Pull request closed without merging**
